Week2
NOW-SOPT-WEB/MinjuneChoi pull request #2
Opened 2024-04-19 06:01 UTC by 202010927choiminjune

## ✨ 구현 기능 명세

- 기본 과제
- 심화 과제
- 공유 과제(링크)

<br />

##  📌 내가 새로 알게 된 부분

- ~ 부분 이렇게 구현했어요, 피드백 부탁해요!

<br />

## 💎 구현과정에서의 고민과정(어려웠던 부분) 공유!
- ~ 부분이 잘 구현한건지 잘 모르겠어요!
- ~부분 다른 방법이 있는지 궁금해요!

<br />

## 🥺 소요 시간
- `6h`

<br />

## 🌈 구현 결과물

2024-04-19 14:28 UTC, ExceptAnyone commented on second session/assignment/shoppingmall.js
> +    var closeBtn = document.getElementsByClassName('close')[0];
오옹 const가 아니라 var를 쓰셨네요?? 이유가 있으실까요?

var와 let, const의 차이에 대해서 알고 계실까요? 
한 번 공부해보셔도 좋을 거 같아요!!

레퍼런스 남겨놓을게요!
https://f-lab.kr/insight/understanding-var-let-const-in-javascript?gad_source=1&gclid=CjwKCAjwrIixBhBbEiwACEqDJZr7p5fGccfDZ5TNMTv3I-60vuHjcRZnEHgbiFAkZukpT2Df-m7NrRoCVREQAvD_BwE

2024-04-19 14:36 UTC, ExceptAnyone commented on second session/assignment/shoppingmall2.js
> +const ITEMS = [
이 부분이 shoppingmall.js와 shoppingmall2.js 에 같이 쓰이고 있네요!

```js
export const ITEMS = 
```

이렇게 export를 붙이면 다른 곳에서도 ITEMS를 쓸 수 있답니다!
그러려면 html에서 script 태그에 type module을 붙여줘야 할거에요 !!
어떤 역할을 하는지는 한 번 찾아보시길 ㅎㅎ

2024-04-19 14:39 UTC, ExceptAnyone commented on second session/assignment/shoppingcart.js
> +}
정규 표현식 사용 👍👍👍👍
다음번에는 Number.toLocaleString()을 사용해봐도 좋을 것 같아요!

2024-04-19 14:40 UTC, ExceptAnyone commented on second session/assignment/shoppingcart.js
> +            <img src="${item.imgSrc}" class="product-image" style="width:30px; height:30px;">
인라인으로 스타일 속성 지정하는 방식은 '지양'하기!

2024-04-22 01:28 UTC, suwonthugger approved these changes
정말 열심히 하신게 느껴졌어요! 저는 js가 많이 어려운데요, 민준님과 서로 배우면서 발전하고싶네요~

2024-04-22 01:28 UTC, suwonthugger commented on second session/assignment/shoppingcart.js
> +}
p5: 정규 표현식 사용하셨군요!  간단하게 toLocaleString()을 사용하는 방법도 추천해 드리고 싶어요~ 아래 링크로 소개해드릴게요! 
https://shape-coding.tistory.com/72

```suggestion
function formatPrice(price) {
    return Number(price).toLocaleString() // price가 이미 Number 타입이라면 Number는 생략해도됩니다
}
```

2024-04-22 01:28 UTC, suwonthugger commented on second session/assignment/shoppingmall.html
> +    <script src="shoppingmall2.js"></script>
p3)  js를 불러올 때 type="module"로 하면 다른 모듈을 import 해서 사용할 수도 있어요~ 관련 링크 첨부해드릴게요
https://inpa.tistory.com/entry/JS-%F0%9F%93%9A-%EB%AA%A8%EB%93%88-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-import-export-%EC%A0%95%EB%A6%AC

```suggestion
 <script src="shoppingmall.js" type="module"></script>
 ```

2024-04-22 01:28 UTC, suwonthugger commented on second session/assignment/shoppingcart.js
> +    var headerIcon = document.querySelector('.header-icon');
p3) var의 여러가지 문제점 ( 재선언 가능, 함수레벨 스코프 ) 등 때문에, var 사용을 권장하지 않고 있어요! 
웬만하면 const를 사용하고, 값이 유동적으로 바뀌어야하는 상황에는 let을 사용하시는건 어떠세요~?
```suggestion
const headerIcon = document.querySelector('.header-icon');
```

2024-04-22 01:28 UTC, suwonthugger commented on second session/assignment/shoppingcart.js
> +    cartItems.splice(index, 1); // 특정 인덱스의 품목을 삭제
p5) splice를 사용하셨군요 기능에 맞게 적절하게 잘 사용하셨네요~~
참고로 말씀드리자면 추후에 다른 기능을 구현하는 코드도 짜게 되실텐데요, 
splice 함수는 기존의 배열 요소를 변형시키게 됩니다. 이렇게 되면 나중에 코드를 짤 때 오류가 생길 가능성이 있습니다! 
그래서 기존배열을 변형시키지 않고 새로운 배열을 만들어 반환하는 filter를 나중에 활용해보셔도 좋을것 같아요!

2024-04-22 01:28 UTC, suwonthugger commented on second session/assignment/shoppingcart.js
> +const confirmPurchaseBtn = document.getElementById('confirmPurchase');
p5) id 값은 getElementById를 사용하셨는데, class 값은 getElementByClassName을 사용하지 않고 querySelector를 사용하신 이유가 궁금합니다!

2024-04-22 01:28 UTC, suwonthugger commented on second session/assignment/shoppingcart.js
> +    modal.style.display = "block";
p5) 오 이렇게 style을 가져와서 사용하는 방법도 있었군요~~ 하나 배워갑니다~~

2024-04-22 01:28 UTC, suwonthugger commented on second session/assignment/shoppingcart.js
> +}
p5) for, while과 같은 반복문 대신 forEach 사용 정말 굿입니다~~

2024-04-22 01:28 UTC, suwonthugger commented on second session/assignment/shoppingmall.js
p5) 오오 상수를 잘 만드셨군요! 이 상수를 분리해서 js 파일을 따로 만들고 난 후, 다른 모듈에서 불러와서 쓰고 싶다면 export const 를 붙이면 딱이겠네요~~
참고하면 좋을 자료를 첨부해드릴게요!
https://ko.javascript.info/import-export

2024-04-22 01:28 UTC, suwonthugger commented on second session/assignment/shoppingmall.js
> +            let array = JSON.parse(localStorage.getItem("mylist")) || [];
p5) 논리연산자를 사용하셨군요! 오오 이렇게해서 로컬스토리지에 아이템이 없을 때는 빈배열로 할당 굿입니다!!!

2024-04-22 01:28 UTC, suwonthugger commented on second session/assignment/shoppingmall2.js
> +            e.preventDefault();
p5) 제가 e.preventDefault()가 익숙하지 않아서 e.preventDefault를 사용하신 구체적인 이유가 궁금해요~~

2024-04-22 01:28 UTC, suwonthugger commented on second session/assignment/shoppingcart.js
> +}
p5) onclick을 사용하셨군요~~ 근데 onclick 을 직접적으로 사용하게되면 재사용성을 해칠 수 있다고 해요~ addEventListener를 사용하시는건 어떠신가요~~~???

2024-04-22 01:28 UTC, suwonthugger commented on second session/assignment/shoppingcart.js
> +}
p5) 이 부분은 어떤 이유로 window객체에 onclick을 주셨는지 배우고싶어요~~

2024-04-22 01:28 UTC, suwonthugger commented on second session/assignment/static/img/인형.jpg
p5) 곰인형이 너무 귀엽네요~~~ 하나 배워갑니다~~~

2024-04-22 01:28 UTC, suwonthugger commented on second session/assignment/shoppingmall2.js
> +    console.log(productslist);
p5) 기능을 다 구현하신 후에는 클라이언트 console에 직접적으로 값들이 노출될 수 있으니, 필요가 없어진 console.log는 정리하시는게 어떠신가요~~~?

2024-04-22 01:28 UTC, suwonthugger commented on second session/assignment/shoppingmall2.js
> +    const productslist = products.filter(product => product.category === "의류");
p5) 적절한 filter 사용 아주 굿입니다~~

2024-04-22 01:35 UTC, suwonthugger requested changes

2024-04-22 01:35 UTC, suwonthugger commented on second session/assignment/shoppingmall.js
> +    },
p5) 오오 상수를 잘 만드셨군요! 이 상수를 분리해서 js 파일을 따로 만들고 난 후, 다른 모듈에서 불러와서 쓰고 싶다면 export const 를 붙이면 딱이겠네요~~
참고하면 좋을 자료를 첨부해드릴게요!
https://ko.javascript.info/import-export

2024-04-22 01:36 UTC, 10tacion approved these changes

2024-04-22 02:45 UTC, suwonthugger approved these changes

2024-04-22 02:45 UTC, suwonthugger commented on second session/assignment/shoppingmall.js
> +    },
p5) 상수를 따로 분리해서 js 파일을 만들고, export 키워드를 사용해 다른 모듈에서 불러와서 쓸 수 있게해도 좋겠네요! 
관련 링크 첨부해드립니다!
https://ko.javascript.info/import-export

```suggestion
export const COPYEDITEMS = [
    { 
        category : "운동용품",
      imgSrc: "./static/img/자전거.jpg",
      altText: "자전거",
      name: "자전거",
      price: "10000"
    },
```

2024-04-22 04:07 UTC, pepperdad reviewed
과제하느라 고생했어!!! 🥧🥧🥧
같이 열심히 하면서 성장하쟈 ㅎㅎ
코멘트 한 번 확인하면 좋을 것 같아~!

2024-04-22 04:07 UTC, pepperdad commented on second session/assignment/shoppingmall.css
> +
```suggestion

```

2024-04-22 04:07 UTC, pepperdad commented on second session/assignment/shoppingmall.html
> +        </div>
p5: 이 html 부분에서 필터링 될 떄 마다 제목을 동적으로 바꾸는 건 어떨까요~?

2024-04-22 04:07 UTC, pepperdad commented on second session/assignment/shoppingmall.js
> +            console.log(event.currentTarget.getAttribute("id"));
p5: 여기서도 console에 값들이 노출될 수 있으니, 정리하는 게 좋아보여요~!

2024-04-22 04:07 UTC, pepperdad commented on second session/assignment/shoppingmall.js
> +                    localStorage.setItem("mylist", JSON.stringify(array));
p3: 여기서 push 함수보다는 이번 공유과제에서 배웠던 배열의 불변성의 법칙을 지키면서 추가하는 건 어떨까~?

```suggestion
                    const newArray = [...array, filterarray[0]];

                    // 로컬 스토리지에 저장. 여기서는 수정된 배열을 다시 저장합니다.
                    localStorage.setItem("mylist", JSON.stringify(newArray));
```

2024-04-22 04:07 UTC, pepperdad commented on second session/assignment/shoppingmall2.js
> +    imgTag.alt = product.altText;
p5: altText 넣어주는 거 너무 좋다!

2024-04-22 04:07 UTC, pepperdad commented on second session/assignment/shoppingmall2.js
> +  }
p4: 필터링 함수들이 category별로 다 따로 작성되어있는데, 하나의 함수로 만들어서 인자로 category를 준다면 중복된 코드를 많이 줄일 수 있을 것 같아~!

2024-04-22 10:29 UTC, 202010927choiminjune commented on second session/assignment/shoppingmall.js
> +    var closeBtn = document.getElementsByClassName('close')[0];
옙 감사합니당~ 한번 살펴보겠습니다!!

2024-04-22 10:30 UTC, HADONGMI commented on second session/assignment/shoppingmall2.js
> +const ITEMS = [
처음에 export를 사용하려고 했는데 실패했습니다 ㅠㅠ 이런 오점이 있었네여... 감사합니당

2024-04-22 10:30 UTC, 202010927choiminjune commented on second session/assignment/shoppingcart.js
> +}
옙 감사합니다~~

2024-04-22 10:31 UTC, HADONGMI commented on second session/assignment/shoppingcart.js
> +            <img src="${item.imgSrc}" class="product-image" style="width:30px; height:30px;">
옙 앞으로 인라인 속성 최대한 사용 안하도록 하겠습니다!!

2024-04-22 10:32 UTC, 202010927choiminjune commented on second session/assignment/shoppingcart.js
> +}
아 toLocaleString()이라는 것도 있었군여 감사합니당

2024-04-22 10:33 UTC, 202010927choiminjune commented on second session/assignment/shoppingmall.html
> +    <script src="shoppingmall2.js"></script>
저도 처음에 import를 사용하려고 했는데 실패했습니다.. 이런 오점이 있었군여!! 주신 링크 사용해서 한번 수정해보겠습니당 감사합니다 :)

2024-04-22 10:33 UTC, 202010927choiminjune commented on second session/assignment/shoppingcart.js
> +    var headerIcon = document.querySelector('.header-icon');
옙 var, let, const의 차이점 다시한번 복기해보겠습니다~

2024-04-22 10:34 UTC, 202010927choiminjune commented on second session/assignment/shoppingcart.js
> +}
아 onclick을 사용하면 이런 치명적인 단점이 있군여 앞으로 addEvenListener를 사용해보겠습니다

2024-04-22 10:35 UTC, 202010927choiminjune commented on second session/assignment/shoppingcart.js
> +    cartItems.splice(index, 1); // 특정 인덱스의 품목을 삭제
옙~~

2024-04-22 10:36 UTC, 202010927choiminjune commented on second session/assignment/shoppingcart.js
> +const confirmPurchaseBtn = document.getElementById('confirmPurchase');
아직까진 querySelector가 저에게 더 익숙해서 사용했습니다.. ㅋㅋ 
앞으로  class 값은 getElementByClassName사용해 보도록 하겠습니다.

2024-04-22 10:36 UTC, 202010927choiminjune commented on second session/assignment/shoppingcart.js
> +    modal.style.display = "block";
옙 ㅎㅎ

2024-04-22 10:37 UTC, 202010927choiminjune commented on second session/assignment/static/img/인형.jpg
ㅎㅎ

2024-04-22 10:38 UTC, 202010927choiminjune commented on second session/assignment/shoppingcart.js
> +}
window.onclick 이벤트 리스너를 설정함으로써, 사용자가 브라우저 창 어디든 클릭할 때마다 해당 함수가 호출됩니다. 그래서 사용자가 모달 창 자체가 아닌 다른 부분을 클릭하면, 모달 창을 닫는 동작을 수행한다는 것을 봤기 때문에 onlick를 추가했습니다.

2024-04-22 10:40 UTC, 202010927choiminjune commented on second session/assignment/shoppingmall2.js
> +    console.log(productslist);
옙 피드백 감사합니다.

2024-04-22 10:41 UTC, 202010927choiminjune commented on second session/assignment/shoppingmall2.js
> +    const productslist = products.filter(product => product.category === "의류");
히힛

2024-04-22 10:42 UTC, 202010927choiminjune commented on second session/assignment/shoppingmall.js
> +    },
저도 처음에 export를 사용하려고 했는데 실패했습니다.. 한번다시 해보겠습니다.

2024-04-22 10:42 UTC, 202010927choiminjune commented on second session/assignment/shoppingmall.html
> +        </div>
옙 피드백 감사합니다

2024-04-22 10:42 UTC, 202010927choiminjune commented on second session/assignment/shoppingmall.js
> +            console.log(event.currentTarget.getAttribute("id"));
옙 감사합니다~

2024-04-22 10:44 UTC, 202010927choiminjune commented on second session/assignment/shoppingmall.js
> +                    localStorage.setItem("mylist", JSON.stringify(array));
옙 찾아보고 반영하겠습니당

2024-04-22 10:44 UTC, 202010927choiminjune commented on second session/assignment/shoppingmall2.js
> +    imgTag.alt = product.altText;
ㅎㅎ

2024-04-22 10:44 UTC, 202010927choiminjune commented on second session/assignment/shoppingmall2.js
> +  }
옙 피드백 감사합니당~~

2024-04-23 06:59 UTC, imddoy approved these changes
js랑 css 모두 주석을 꼼꼼하게 작성한것 보고 감탄했습니다!
코드에서 열정과 노력이 많이 느껴져서 자극도 많이 받았구,
새로운 것들도 많이 알아갈 수 있었습니다ㅎㅎ
감사합니다.🙇🏻‍♀️🙇🏻‍♀️

2024-04-23 06:59 UTC, imddoy commented on second session/assignment/shoppingcart.html
> +          </tr>
p3: js에서 table을 비우도록 작성하셨는데 이 코드를 작성하신 이유가 궁금합니다!

2024-04-23 06:59 UTC, imddoy commented on second session/assignment/shoppingcart.js
> +    var headerIcon = document.querySelector('.header-icon');
p5: 저두 공부하고 갑니다~

2024-04-23 06:59 UTC, imddoy commented on second session/assignment/shoppingcart.js
> +}
p5: 저두 공부하고 갑니다 22~

2024-04-23 06:59 UTC, imddoy commented on second session/assignment/shoppingmall2.js
> +    });
p5: 이렇게 섹션을 숨기는 방법도 있었네요!! 하나 알아갑니다~~ㅎㅎ

2024-04-23 08:10 UTC, suwonthugger commented on second session/assignment/shoppingcart.js
> +const confirmPurchaseBtn = document.getElementById('confirmPurchase');
아하 그렇군요~~~ 민준님이 상황에 맞게 적절히 사용하시면 좋을것 같아요 답변 감사합니두

2024-04-23 08:10 UTC, suwonthugger commented on second session/assignment/shoppingcart.js
> +}
아하 그렇군요~~

2024-04-24 11:14 UTC, 202010927choiminjune commented on second session/assignment/shoppingcart.js
> +}
히히

2024-04-24 11:14 UTC, 202010927choiminjune commented on second session/assignment/shoppingmall.js
> +            let array = JSON.parse(localStorage.getItem("mylist")) || [];
감사합니다~

2024-04-24 11:20 UTC, 202010927choiminjune commented on second session/assignment/shoppingmall2.js
> +            e.preventDefault();
e.preventDefault();

클릭 이벤트의 기본 작동을 중단합니다.  예를 들어, 링크(<a>) 요소의 경우, 링크를 클릭했을 때 페이지가 다른 주소로 이동하는 기본 동작을 중지시킵니다.

랜더링할 때에 선택한 것 이외의 기본동작들을 중단시키기 위해서 사용?!했습니다.

2024-04-24 11:22 UTC, 202010927choiminjune commented on second session/assignment/shoppingcart.html
> +          </tr>
앗 제가 아직 거기까지 하기엔 역량이 충분하지 못한 거같습니다 ㅜㅜ의견주셔서 너무 감사하고 반영하겠습니당~

2024-04-24 11:22 UTC, 202010927choiminjune commented on second session/assignment/shoppingmall2.js
> +    });
옙~~

2024-04-24 11:25 UTC, merged